[package]
name = "hello-ort"
version = "0.0.0"
edition = "2021"

[dependencies]
ort = { git = "https://github.com/pykeio/ort", features = [
    "ndarray", "download-binaries", "fetch-models"
], default-features = false }
ndarray = "0.16"
anyhow = "1"